---
resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: latest
- name: artifactory
  type: docker-image
  source:
    repository: pivotalservices/artifactory-resource
- name: ansible
  type: docker-image
  source:
    repository: platformengineering/concourse-ansible-resource
- name: pull-request
  type: docker-image
  source:
    repository: jtarchie/pr
    tag: latest

groups:
  - name: Build
    jobs: 
      - build
  - name: NonProductionDeployment
    jobs:
      - deploy-to-development

resources:
  - name: artifactory-repository
    type: artifactory
    check_every: 1m
    source:
      endpoint: https://artifactory.io.comcast.net
      repository: "/libs-snapshot-local"
      regex: "concourse-web-(?<version>.*).jar"
      username: "!spectra"
      password: "spectra1!"
  - name: concourse-web
    type: git
    source:
      uri: https://github.com/satishnaidu/concourse-web.git
      branch: develop
      username: satishnaidu
      password: Sunday@23
      ignore_paths:
        - pom.xml
  - name: push-concourse-web
    type: git
    source:
      uri: https://github.com/satishnaidu/concourse-web.git
      branch: develop
      username: satishnaidu
      password: Sunday@23

jobs:
  - name: build
    serial: true
    plan:
      - get: concourse-web
        trigger: true
      - task: run-build
        file: concourse-web/ci/tasks/run_build.yml
        params:
          ARTIFACTORY_USER: '!spectra'
          ARTIFACTORY_PW: spectra1!
          ARTIFACTORY_URL: https://artifactory.io.comcast.net/libs-snapshot-local
      - put: push-concourse-web
        params: {repository: updated-concourse-web}
      - put: artifactory-repository
        params: { file: ./artifactory-repository/concourse-web-*.jar }

  - name: deploy-to-development
    serial: true
    plan:
      - get: concourse-web
        passed: [build]
      - task: deploy-dev
        file: concourse-web/ci/tasks/deploy_to_dev.yml
        params:
          ARTIFACTORY_USER: '!spectra'
          ARTIFACTORY_PW: spectra1!
          ARTIFACTORY_URL: https://artifactory.io.comcast.net/libs-snapshot-local
      
        