---

resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: latest
- name: artifactory
  type: docker-image
  source:
    repository: pivotalservices/artifactory-resource

groups:
  - name: Build
    jobs: 
      - release-candidate-version
      - build

resources:
  - name: artifactory-repository
    type: artifactory
    check_every: 1m
    source:
      endpoint: https://artifactory.io.comcast.net
      repository: "/libs-snapshot-local"
      regex: "concourse-web-(?<version>.*).jar"
      username: '!spectra'
      password: spectra1!
  - name: concourse-web
    type: git
    source:
      uri: https://github.com/satishnaidu/concourse-web.git
      branch: develop
      username: satishnaidu
      password: Sunday@23
  - name: version
    type: semver
    source:
      driver: git
      uri: https://gist.github.com/ef4361ca808a7b41fe7c9551467d81f6.git
      branch: master
      file: concourse-web.version
      username: satishnaidu
      password: Sunday@23
  - name: slack-alert
    type: slack-notification
    source: 
      url: https://hooks.slack.com/services/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

jobs:
  - name: release-candidate-version
    serial: true
    plan:
      - get: concourse-web
        trigger: true
      - get: version
        params: {pre: rc}
      - put: version
        params: {file: version/number}
      - task: update-version
        file: concourse-web/ci/tasks/version_source.yml
      - put: concourse-web
        params: {repository: updated-concourse-web}
        on_success:
          do:
          - put: slack-alert
            params:
              channel: '#concourse-np-updates'
              text: "From NP concourse pipeline: build status: passed"
        on_failure:
          do:
          - put: slack-alert
            params:
              channel: '#concourse-np-updates'
              text: "From NP concourse pipeline: build status: failed"
  - name: build
    plan:
      - get: version
        trigger: true
        passed: [release-candidate-version]
      - get: concourse-web
        trigger: true
        passed: [release-candidate-version]
      - task: run-build
        file: concourse-web/ci/tasks/run_build.yml
        params:
          ARTIFACTORY_USER: '!spectra'
          ARTIFACTORY_PW: spectra1!
          ARTIFACTORY_URL: https://artifactory.io.comcast.net/libs-snapshot-local
      - put: artifactory-repository
        params: { file: ./artifactory-repository/concourse-web-*.jar }
        